### ISSUE TITLE
Add assessment-related endpoints to binding with basic API test

### ISSUE THREAD

**Issue by aufi** [konveyor/tackle2-hub#494]
```[tasklist]
### Tasks
- [x] questionnaire https://github.com/konveyor/tackle2-hub/pull/492
- [x] assessment https://github.com/konveyor/tackle2-hub/pull/562
- [x] archetype https://github.com/konveyor/tackle2-hub/pull/563
```

**Comment by aufi** [comment]
Done by end of 2023.
